images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer-equinixmetal
  tag: "v2.22.0"
- name: cloud-controller-manager
  sourceRepository: github.com/equinix/cloud-provider-equinix-metal
  repository: eu.gcr.io/gardener-project/3rd/equinix/cloud-provider-equinix-metal
  tag: v3.6.2
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.49.2"
- name: machine-controller-manager-provider-equinix-metal
  sourceRepository: github.com/gardener/machine-controller-manager-provider-equinix-metal
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-equinix-metal
  tag: "v0.6.0"
- name: metabot
  sourceRepository: github.com/packethost/metabot
  repository: eu.gcr.io/gardener-project/3rd/packethost/metabot
  tag: v1.0.0
- name: metallb-controller
  sourceRepository: github.com/metallb/metallb
  repository: quay.io/metallb/controller
  tag: v0.12.1
- name: metallb-speaker
  sourceRepository: github.com/metallb/metallb
  repository: quay.io/metallb/speaker
  tag: v0.12.1
