images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer-equinixmetal
  tag: "v2.11.0"
- name: cloud-controller-manager
  sourceRepository: github.com/equinix/cloud-provider-equinix-metal
  repository: docker.io/equinix/cloud-provider-equinix-metal
  tag: v3.2.0
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.42.0"
- name: machine-controller-manager-provider-equinix-metal
  sourceRepository: github.com/gardener/machine-controller-manager-provider-equinix-metal
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-equinix-metal
  tag: "v0.3.0"
- name: metabot
  sourceRepository: github.com/packethost/metabot
  repository: packethost/metabot
  tag: v1.0.0
- name: metallb-controller
  sourceRepository: github.com/metallb/metallb
  repository: quay.io/metallb/controller
  tag: v0.9.5
- name: metallb-speaker
  sourceRepository: github.com/metallb/metallb
  repository: quay.io/metallb/speaker
  tag: v0.9.5
